name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    name:    Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build Common
        uses: actions/checkout@v2.3.2
        with:
          path:       build-common
          repository: paketo-buildpacks/build-common
      - name: Checkout Source
        uses: actions/checkout@v2.3.2
        with:
          path: source
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: go-cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run:  build-common/test.sh
